<#
	.SYNOPSIS
		Displays a message using the colors and verbosity level specified by the user.

	.DESCRIPTION
		This function display a message using one of four possible native PowerShell cmdlets using the foreground and background colors specified by the user.

		This function will use either the Write-Debug, Write-Error, Write-Verbose or Write-Warning cmdlets to display the specified message.

		All color names that can be used for the Write-Host cmdlet can be used with this function.

	.PARAMETER Message
		This is the text that will be written using one of PowerShell's native Write-* cmdlets.

	.PARAMETER WriteAs
		This is the name of the PowerShell write cmdlet to use.

		Valid values are:
		-- Debug
		-- Error
		-- Verbose
		-- Warning

	.PARAMETER BackgroundColor
		The name of the color to use for the background. These values are the same as the Write-Host cmdlet.

	.PARAMETER ForegroundColor
		The name of the color to use for the foreground/text color. These values are the same as the Write-Host cmdlet.

	.EXAMPLE
		Write-ColorizedMessage -BackgroundColor Blue -ForegroundColor Green

		Writes the default message with the background and foreground (text) colors specified.

	.EXAMPLE
		"Yes", "No", "Maybe" | Write-ColorizedMessage -WriteAs Warning -ForegroundColor Magenta

		Writes each of the messages piped to the function using PowerShell's Write-Warning cmdlet. Each message is written with magenta-colored text.

	.EXAMPLE
		Write-ColorizedMessage -Message ("Hello misleading error") -WriteAs Error -BackgroundColor Green

		Writes the specified message using PowerShell's Write-Error cmdlet. The background of the message will be green.

	.INPUTS
		Strings representing messages to write can be passed through the pipeline to this function.

	.OUTPUTS
		No output is generated by this function.

	.NOTES
		This function currently does not support all of the additional parameters that can be used with the Write-Error cmdlet. Please use the Write-Error cmdlet if you would like to use its additional parameters.

		Error messages will only be displayed if the -Debug and -Verbose messages will only be displayed if those flags have been specified by functions/cmdlets calling this function.

		This function is licensed under the MIT license for Dodzidenu Y. Dzakuma

	.LINK
		about_Functions_Advanced_Parameters

	.LINK
		Write-Host

	.LINK
		Write-Debug

	.LINK
		Write-Error

	.LINK
		Write-Verbose

	.LINK
		Write-Warning
#>
function Write-ColorizedMessage
{
	[CmdletBinding()]
	param (
		[ValidateNotNullOrEmpty()]
		[parameter(Position=0,ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true)]
		[string[]]$Message=$null,
		
		[ValidateNotNullOrEmpty()]
		[ValidateSet("Debug","Error","Verbose","Warning")]
		[string]$WriteAs="Verbose",

		[ValidateNotNullOrEmpty()]
		[ValidateSet("Black","Blue","Cyan","DarkBlue","DarkCyan","DarkGray","DarkGreen","DarkMagenta","DarkRed","DarkYellow","Gray","Green","Magenta","Red","White","Yellow")]
		[string]$BackgroundColor=$null,

		[ValidateNotNullOrEmpty()]
		[Alias("TextColor")]
		[ValidateSet("Black","Blue","Cyan","DarkBlue","DarkCyan","DarkGray","DarkGreen","DarkMagenta","DarkRed","DarkYellow","Gray","Green","Magenta","Red","White","Yellow")]
		[string]$ForegroundColor=$null
	)
	begin
	{
		if ([System.string]::IsNullOrEmpty($Message))
		{
			$Message = "This is the default [{0}] message." -f $WriteAs
		}

		$hostVariables = (Get-Host).PrivateData
		$originalBackgroundColor = $hostVariables."${WriteAs}BackgroundColor"
		$originalForegroundColor = $hostVariables."${WriteAs}ForegroundColor"

		$selectedBackgroundcolor = if ($BackgroundColor) { $BackgroundColor } else { $originalBackgroundColor }
		$selectedForegroundColor = if ($ForegroundColor) { $ForegroundColor } else { $originalForegroundColor }

		$hostVariables."${WriteAs}BackgroundColor" = $selectedBackgroundcolor
		$hostVariables."${WriteAs}ForegroundColor" = $selectedForegroundColor
	}
	process
	{
		$Message | ForEach-Object -Process {
			switch ($WriteAs)
			{
				Debug { Write-Debug -Message $_ }
				Error { Write-Error -Message $_ }
				Verbose { Write-Verbose -Message $_ }
				Warning { Write-Warning -Message $_ }
			}
		}
	}
	end
	{
		$hostVariables."${WriteAs}BackgroundColor" = $originalBackgroundColor
		$hostVariables."${WriteAs}ForegroundColor" = $originalForegroundColor
	}
}